# Generated by Django 4.0.5 on 2022-06-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='date',
        ),
        migrations.AddField(
            model_name='experience',
            name='start',
            field=models.DateField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='to',
            field=models.DateField(max_length=200, null=True),
        ),
    ]
